以下のような行列A、Bを考えます。

$$
\boldsymbol{A} = \left[\begin{array}{c}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{array}\right]
,
\boldsymbol{B} = \left[\begin{array}{c}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{array}\right]
$$

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

### 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。

#### 解答
行列$\boldsymbol{A}, \boldsymbol{B}$を以下のように表したときの行列式を考える。

$$
\boldsymbol{A} = \left[\begin{array}{c}
a_{0,0} & a_{0,1} & a_{0,2} \\
a_{1,0} & a_{1,1} & a_{1,2} \\
a_{2,0} & a_{2,1} & a_{2,2} \\
\end{array}\right]
,
\boldsymbol{B} = \left[\begin{array}{c}
b_{0,0} & b_{0,1} & b_{0,2} \\
b_{1,0} & b_{1,1} & b_{1,2} \\
b_{2,0} & b_{2,1} & b_{2,2} \\
\end{array}\right]
$$

$$
\boldsymbol{A・B} = \left[\begin{array}{c}
a_{0,0}・b_{0,0}+a_{0,1}・b_{1,0}+a_{0,2}・b_{2,0} & a_{0,0}・b_{0,1}+a_{0,1}・b_{1,1}+a_{0,2}・b_{2,1} & a_{0,0}・b_{0,2}+a_{0,1}・b_{1,2}+a_{0,2}・b_{2,2} \\
a_{1,0}・b_{0,0}+a_{1,1}・b_{1,0}+a_{1,2}・b_{2,0} & a_{1,0}・b_{0,1}+a_{1,1}・b_{1,1}+a_{1,2}・b_{2,1} & a_{1,0}・b_{0,2}+a_{1,1}・b_{1,2}+a_{1,2}・b_{2,2} \\
a_{2,0}・b_{0,0}+a_{2,1}・b_{1,0}+a_{2,2}・b_{2,0} & a_{2,0}・b_{0,1}+a_{2,1}・b_{1,1}+a_{2,2}・b_{2,1} & a_{2,0}・b_{0,2}+a_{2,1}・b_{1,2}+a_{2,2}・b_{2,2}
\end{array}\right]
$$

上記の式に、行列$\boldsymbol{A}, \boldsymbol{B}$の値を代入する。

$$
\boldsymbol{A・B} = \left[\begin{array}{c}
-1・0+2・0+3・2 \quad -1・2+2・2+3・9 \quad -1・1+2・-8+3・-1 \\
4・0+-5・0+6・2 \quad 4・2+-5・2+6・9 \quad 4・1+-5・-8+6・-1 \\
7・0+8・0+-9・2 \quad 7・2+8・2+-9・9 \quad 7・1+8・-8+-9・-1
\end{array}\right] \\
=\left[\begin{array}{c}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{array}\right]
$$


### 【問題2】NumPyの関数による計算
この行列積はNumPyの`np.matmul()`や`np.dot()`、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

In [2]:
mp_AB = np.dot(a_ndarray, b_ndarray)
print(mp_AB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [3]:
mp_AB = np.matmul(a_ndarray, b_ndarray)
print(mp_AB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [4]:
mp_AB = a_ndarray @ b_ndarray
print(mp_AB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


行列Aの(0,0)の要素 $a_{0, 0}$ と行列Bの(0,0)の要素 $b_{0, 0}$ を掛け合わせる
行列Aの(0,1)の要素 $a_{0, 1}$ と行列Bの(1,0)の要素 $b_{1, 0}$ を掛け合わせる
行列Aの(0,2)の要素 $a_{0, 2}$ と行列Bの(2,0)の要素 $b_{2, 0}$ を掛け合わせる
それらの値を全て足し合わせる

数式で表すと

$$
\sum_{k=0}^{2}a_{0,k}b_{k,0}
$$

です。


この計算を`np.matmul()`や`np.dot()`、または@演算子を使わずに行うコードを書いてください。

In [22]:
tmp_array = a_ndarray[0] * b_ndarray[:, 0]
print(sum(tmp_array))

6


### 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。

行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。

計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。

$$
c_{i,j} = \sum_{k=0}^{2}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。

In [71]:
def compute_mp(matrix_A, matrix_B):

    list_mp_AB = []

    for a in matrix_A:
        for cnt in range(matrix_B.shape[1]):
            tmp_array = a * matrix_B[:, cnt]
            list_mp_AB.append(sum(tmp_array))

    return np.reshape(list_mp_AB, (3, 3))

In [72]:
mp_AB = compute_mp(a_ndarray, b_ndarray)
mp_AB

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

---

次に以下のような例を考えます。

$$
\boldsymbol{D} = \left[\begin{array}{c}
-1 & 2 & 3 \\
4 & -5 & 6 
\end{array}\right]
,
\boldsymbol{E} = \left[\begin{array}{c}
-9 & 8 & 7 \\
6 & -5 & 4 
\end{array}\right]
$$

In [73]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

### 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。

if文などによってこれを防ぎ、入力される形に問題があることを`print()`を使い表示するコードを書き加えてください。

In [79]:
def compute_mp_kai(matrix_A, matrix_B):

    # 入力チェック
    if matrix_A.shape[1] != matrix_B.shape[0]:
        print("行列積を計算できる入力ではありません")
        print("matrix_A.shape:{}".format(matrix_A.shape))
        print("matrix_B.shape:{}".format(matrix_B.shape))
        return 
    
    list_mp_AB = []

    for a in matrix_A:
        for cnt in range(matrix_B.shape[1]):
            tmp_array = a * matrix_B[:, cnt]
            list_mp_AB.append(sum(tmp_array))

    return np.reshape(list_mp_AB, (matrix_A.shape[0], matrix_B.shape[1]))

In [80]:
print(compute_mp_kai(d_ndarray, e_ndarray))

行列積を計算できる入力ではありません
matrix_A.shape:(2, 3)
matrix_B.shape:(2, 3)
None


### 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。

In [81]:
print(d_ndarray.T)
print(e_ndarray)
print(compute_mp_kai(d_ndarray.T, e_ndarray))

[[-1  4]
 [ 2 -5]
 [ 3  6]]
[[-9  8  7]
 [ 6 -5  4]]
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]


In [82]:
print(d_ndarray)
print(e_ndarray.T)
print(compute_mp_kai(d_ndarray, e_ndarray.T))

[[-1  2  3]
 [ 4 -5  6]]
[[-9  6]
 [ 8 -5]
 [ 7  4]]
[[ 46  -4]
 [-34  73]]
